# Generated by Django 2.1 on 2020-04-15 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='delivery_tip',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
