# Generated by Django 2.1 on 2020-04-18 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20200418_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemaddcategory',
            name='multi',
            field=models.BooleanField(default=False),
        ),
    ]
